### ISSUE TITLE
how to apply fill attribute in vue3?

### ISSUE THREAD

**Issue by 19park** [shrpne/vue-inline-svg#42]
![image](https://user-images.githubusercontent.com/26448546/185541928-058dd33a-2433-4f7f-94bd-e38bc7af0c6f.png)
I passed the fill attribute, but it doesn't change.

![image](https://user-images.githubusercontent.com/26448546/185542044-cbe3a4e1-d4ca-4ea3-bcb3-0c6940c7e1ba.png)

thank you.

**Comment by shrpne** [comment]
Attributes passed to VueInlineSvg component are only applied to the root svg node. So `fill` attribute on the `path` element is used instead of `fill` on the `svg`

There are two solutions:
1. Edit your svg file: move `fill` from `path` to `svg` so applied attribute can override it.
2. use [transformSource](https://github.com/shrpne/vue-inline-svg#--transformsource) function to edit `path`'s fill dynamically
