### ISSUE TITLE
Remove style-element from svg

### ISSUE THREAD

**Issue by manuelkling** [shrpne/vue-inline-svg#59]
Hey guys, thank you for this great component!

When you export svgs f.e. with Adobe Illustrator, there is always a style-element in the svg giving the path a color. At the moment we just delete it manually. Would be great to have a prop like "removeStyle" to look for it inside the svg and remove when importing it. What do you think?

**Comment by shrpne** [comment]
Thank you for suggestion. But i'm trying to keep the library minimal, I guess this option will not be used much, since having redundant code in SVG markup is bad for performance reason, and preprocessing SVG sources by cleaning them is good idea.

Anyway you can workaround it by using [transformSource](https://github.com/shrpne/vue-inline-svg?tab=readme-ov-file#--transformsource) function to remove style
